services:
  api:
    build: .
    container_name: agentresume-api
    ports:
      - "8001:8000"
    env_file:
      - .env

  ui:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: agentresume-ui
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api:8000
    depends_on:
      - api